### ISSUE TITLE
Error on `brew cu`

### ISSUE THREAD

**Issue by luisspuerto** [buo/homebrew-cask-upgrade#103]
```
$ brew cu
==> Options
Include auto-update (-a): false
Include latest (-f): false
==> Updating Homebrew
Error: uninitialized constant Hbc::SystemCommand
Did you mean?  SystemCommand
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:56:in `brew_update'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:20:in `process'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:34:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:18:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

**Comment by ydesgagn** [comment]
Same here.

**Comment by singularitti** [comment]
This same to happen after commit [#4517](https://github.com/Homebrew/brew/pull/4517).

**Comment by karanbhamra** [comment]
I fixed it by editing the file: /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb

on line 56 get rid of the Hbc::    before the SystemCommand and it should look like SystemCommand.run(HOMEBREW_BREW_FILE, args: ["update"], print_stderr: true, print_stdout: false)

save it and then run command again to check for update and it should work.

**Comment by huntout** [comment]
@karanbhamra thanks, it works. maybe you should pull a request.

**Comment by KarlZeo** [comment]
[I fix it and create new pr](https://github.com/buo/homebrew-cask-upgrade/pull/104)

**Comment by ljakab** [comment]
Same here.

**Comment by FateLight** [comment]
@karanbhamra thx,it work.

**Comment by KarlZeo** [comment]
@buo please close this issues,because bug is fix
