### ISSUE TITLE
brew cu fails with "Error: cannot load such file -- hbc"

### ISSUE THREAD

**Issue by csi-adziahel** [buo/homebrew-cask-upgrade#109]
Repro:

1. Run `brew cu`

Expected: normal run
Instead: it fails with runtime error

Console output:

```
⋊> ~  brew cu                                                                                                                                                                                           14:00:29
Error: cannot load such file -- hbc
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:4:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:32:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.7/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:19:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'
```

**Comment by csi-adziahel** [comment]
looks like caused by https://github.com/Homebrew/brew/commit/90b3a139092b5a24bf54715c09c46d7c838ddedf

**Comment by ondrejfuhrer** [comment]
Thanks for the report @csi-adziahel , feel free to use my branch until @buo merge the fix.

**Comment by y0y0z** [comment]
probably duplicate: https://github.com/buo/homebrew-cask-upgrade/issues/111
but leaving it for extra information.

**Comment by daylightbrightledlight** [comment]
I also get this bug (same as #111).
