### ISSUE TITLE
Always get status code 416 while upgrading FileZilla

### ISSUE THREAD

**Issue by matteodisabatino** [buo/homebrew-cask-upgrade#121]
Hello all,
it's about a week that I'm unable to update FileZilla, the current situation is the following:
When I type `brew cu -ay` I receive this message:

```
==> Upgrading filezilla to 3.37.1
==> Satisfying dependencies
==> Downloading https://download.filezilla-project.org/client/FileZilla_3.37.1_macosx-x86.app.tar.bz2
######################################################################## 100.0%
curl: (22) The requested URL returned error: 416
Error: Download failed on Cask 'filezilla' with message: Download failed: https://download.filezilla-project.org/client/FileZilla_3.37.1_macosx-x86.app.tar.bz2
```

The URL is correct because if I go with my browser I can download the file. By typing `brew cask install filezilla --debug` I get more information that I hope could be helpful to solve the problem:

```
==> Cask::Installer#install
==> Printing caveats
==> Cask::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download.filezilla-project.org/client/FileZilla_3.37.1_macosx-x86.app.tar.bz2
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.6-22-gdae4791\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head https://download.filezilla-project.org/client/FileZilla_3.37.1_macosx-x86.app.tar.bz2
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.6-22-gdae4791\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --silent --head https://download.filezilla-project.org/client/FileZilla_3.37.1_macosx-x86.app.tar.bz2
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.6-22-gdae4791\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --location --head --range 0-1 --write-out \%\{http_code\} --output /dev/null https://download.filezilla-project.org/client/FileZilla_3.37.1_macosx-x86.app.tar.bz2
/usr/bin/curl -q --show-error --user-agent Homebrew/1.7.6-22-gdae4791\ \(Macintosh\;\ Intel\ Mac\ OS\ X\ 10.13.6\)\ curl/7.54.0 --fail --progress-bar --location --remote-time --continue-at - --output /Users/disa/Library/Caches/Homebrew/downloads/5d7f52e62a8aa28b7846c1b412980684be0836e5cd596da5fc10397fb5291762--FileZilla_3.37.1_macosx-x86.app.tar.bz2.incomplete https://download.filezilla-project.org/client/FileZilla_3.37.1_macosx-x86.app.tar.bz2
######################################################################## 100.0%
curl: (22) The requested URL returned error: 416
Error: Download failed on Cask 'filezilla' with message: Download failed: https://download.filezilla-project.org/client/FileZilla_3.37.1_macosx-x86.app.tar.bz2
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:295:in `rescue in fetch'
/usr/local/Homebrew/Library/Homebrew/download_strategy.rb:290:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:40:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/download.rb:18:in `perform'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:146:in `download'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:62:in `fetch'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:90:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:21:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:89:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:160:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:143:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:120:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:7:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:91:in `<main>'
```

**Comment by ondrejfuhrer** [comment]
Hey @matteodisabatino , thanks for reporting, but there is unfortunately nothing we can do about it here. This is the cask issue and is described here: https://github.com/Homebrew/homebrew-cask/issues/52149

Please close this issue and continue watching it there 🙂

**Comment by matteodisabatino** [comment]
Thank you for information @ondrejfuhrer :-). I close the issue.
