### ISSUE TITLE
brew doctor reports error for homebrew-cask-upgrade

### ISSUE THREAD

**Issue by mr-narender** [buo/homebrew-cask-upgrade#228]
Here's error snippet from console:

```
🚀 brew doctor                                                                                  took 170ms ~
Error: undefined method `git_default_origin_branch?' for #<Pathname:/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade>
Please report this issue:
  https://docs.brew.sh/Troubleshooting
/opt/homebrew/Library/Homebrew/diagnostic.rb:548:in `block in check_tap_git_branch'
/opt/homebrew/Library/Homebrew/tap.rb:750:in `block (2 levels) in each'
/opt/homebrew/Library/Homebrew/tap.rb:749:in `each'
/opt/homebrew/Library/Homebrew/tap.rb:749:in `block in each'
/opt/homebrew/Library/Homebrew/tap.rb:748:in `each'
/opt/homebrew/Library/Homebrew/tap.rb:748:in `each'
/opt/homebrew/Library/Homebrew/diagnostic.rb:547:in `map'
/opt/homebrew/Library/Homebrew/diagnostic.rb:547:in `check_tap_git_branch'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:62:in `block in doctor'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:55:in `each'
/opt/homebrew/Library/Homebrew/cmd/doctor.rb:55:in `doctor'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
🚀
```

**Comment by ondrejfuhrer** [comment]
@mr-narender Is that still the case? I tried running doctor on my machine and seems to be all right? Maybe that was just a temporary issue?

**Comment by mr-narender** [comment]
seems like this is all right after a reset. closing this for now.
