### ISSUE TITLE
Error: undefined method `versions' for Cask

### ISSUE THREAD

**Issue by m-zheng** [buo/homebrew-cask-upgrade#231]
I believe the recent homebrew update has somehow broken the pin function. Error messages are shown below when I execute `brew cu pin firefox`. Interestingly, firefox still gets pinned afterwards.

```
Error: undefined method `versions' for #<Cask::Cask:0x000000012ddab2a8>
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu/command/pin_add.rb:39:in `run_add_pin'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu/command/pin_add.rb:19:in `add_pin'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu/command/pin_add.rb:13:in `process'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:25:in `process'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:75:in `<top (required)>'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:10:in `require'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:10:in `require?'
/opt/homebrew/Library/Homebrew/brew.rb:96:in `<main>'

```

**Comment by fengci** [comment]
I had an error after brew cu update, then I continued to execute brew cu pin and also had your error, then I reopened the shell and re-executed and it was fine
