### ISSUE TITLE
Error: "!contains invalid characters:"

### ISSUE THREAD

**Issue by Sophoria** [buo/homebrew-cask-upgrade#260]
I'm getting this after I updated to Sequoia (15.0.1 on MacMini M1);
I've tried untapping/retapping, brew doctor (clean), repeated brew update/upgrade, rebooting... but the problem continues.

==> Options
Include auto-update (-a): false
Include latest (-f): false
==> Updating Homebrew
==> Updating Homebrew...
Already up-to-date.
!contains invalid characters:
/opt/homebrew/Library/Homebrew/cask/dsl/version.rb:71:in `initialize'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:14:in `new'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:14:in `current_version'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:26:in `block in installed_apps'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:22:in `map'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:22:in `installed_apps'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu/command/upgrade.rb:31:in `run_process'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu/command/upgrade.rb:8:in `process'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:24:in `process'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:75:in `<top (required)>'
<internal:/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:11:in `require?'
/opt/homebrew/Library/Homebrew/brew.rb:100:in `<main>'

**Comment by ondrejfuhrer** [comment]
Hey @Sophoria , it's probably an issue in one of the installed casks. Can you please give us the output of this?

```bash
brew outdated --cask
```

**Comment by sherySJ** [comment]
Same issue here with my m1 macbook air running sequioa 15.1 beta 6, tried running `brew outdated --cask` but the issue still persists
```==> Options
Include auto-update (-a): true
Include latest (-f): true
Include mac app store (--include-mas): true
==> Updating Homebrew
==> Updating Homebrew...
Already up-to-date.

Error: 16.89.24091630 1-59-15-667 PM.24091630 contains invalid characters:  !
Warning: Removed Sorbet lines from backtrace!
Rerun with `--verbose` to see the original backtrace
/opt/homebrew/Library/Homebrew/cask/dsl/version.rb:71:in `initialize'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:14:in `new'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:14:in `current_version'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:26:in `block in installed_apps'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:22:in `map'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:22:in `installed_apps'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu/command/upgrade.rb:31:in `run_process'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu/command/upgrade.rb:8:in `process'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:24:in `process'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:75:in `<top (required)>'
<internal:/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:11:in `require?'
/opt/homebrew/Library/Homebrew/brew.rb:100:in `<main>'```

**Comment by sherySJ** [comment]
This is what running `brew cu --verbose` returns
```
==> Options
Include auto-update (-a): false
Include latest (-f): false
==> Updating Homebrew
Checking if we need to fetch /opt/homebrew...
==> Updating Homebrew...
Checking if we need to fetch /opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade...
Checking if we need to fetch /opt/homebrew/Library/Taps/dart-lang/homebrew-dart...
Checking if we need to fetch /opt/homebrew/Library/Taps/homebrew/homebrew-autoupdate...
Checking if we need to fetch /opt/homebrew/Library/Taps/homebrew/homebrew-bundle...
Checking if we need to fetch /opt/homebrew/Library/Taps/homebrew/homebrew-services...
Checking if we need to fetch /opt/homebrew/Library/Taps/isen-ng/homebrew-dotnet-sdk-versions...
Checking if we need to fetch /opt/homebrew/Library/Taps/leoafarias/homebrew-fvm...
Checking if we need to fetch /opt/homebrew/Library/Taps/lihaoyun6/homebrew-tap...
Checking if we need to fetch /opt/homebrew/Library/Taps/microsoft/homebrew-git...
Checking if we need to fetch /opt/homebrew/Library/Taps/mongodb/homebrew-brew...
Checking if we need to fetch /opt/homebrew/Library/Taps/romkatv/homebrew-powerlevel10k...
Checking if we need to fetch /opt/homebrew/Library/Taps/rstacruz/homebrew-backup...
Checking if we need to fetch /opt/homebrew/Library/Taps/sidneys/homebrew-homebrew...
Fetching /opt/homebrew...
Fetching /opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade...
Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-bundle...
Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-autoupdate...
Fetching /opt/homebrew/Library/Taps/dart-lang/homebrew-dart...
Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-services...
Fetching /opt/homebrew/Library/Taps/isen-ng/homebrew-dotnet-sdk-versions...
Fetching /opt/homebrew/Library/Taps/lihaoyun6/homebrew-tap...
Fetching /opt/homebrew/Library/Taps/leoafarias/homebrew-fvm...
Fetching /opt/homebrew/Library/Taps/microsoft/homebrew-git...
Fetching /opt/homebrew/Library/Taps/mongodb/homebrew-brew...
Fetching /opt/homebrew/Library/Taps/rstacruz/homebrew-backup...
Fetching /opt/homebrew/Library/Taps/romkatv/homebrew-powerlevel10k...
Fetching /opt/homebrew/Library/Taps/sidneys/homebrew-homebrew...
Checking if we need to fetch formula.jws.json...
Checking if we need to fetch cask.jws.json...
Checking if we need to fetch formula_tap_migrations.jws.json...
Checking if we need to fetch cask_tap_migrations.jws.json...
Already up-to-date.
Checking if we need to fetch /opt/homebrew...
Checking if we need to fetch /opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade...
Checking if we need to fetch /opt/homebrew/Library/Taps/dart-lang/homebrew-dart...
Checking if we need to fetch /opt/homebrew/Library/Taps/homebrew/homebrew-autoupdate...
Checking if we need to fetch /opt/homebrew/Library/Taps/homebrew/homebrew-bundle...
Checking if we need to fetch /opt/homebrew/Library/Taps/homebrew/homebrew-services...
Checking if we need to fetch /opt/homebrew/Library/Taps/isen-ng/homebrew-dotnet-sdk-versions...
Checking if we need to fetch /opt/homebrew/Library/Taps/leoafarias/homebrew-fvm...
Checking if we need to fetch /opt/homebrew/Library/Taps/lihaoyun6/homebrew-tap...
Checking if we need to fetch /opt/homebrew/Library/Taps/microsoft/homebrew-git...
Checking if we need to fetch /opt/homebrew/Library/Taps/mongodb/homebrew-brew...
Checking if we need to fetch /opt/homebrew/Library/Taps/romkatv/homebrew-powerlevel10k...
Checking if we need to fetch /opt/homebrew/Library/Taps/rstacruz/homebrew-backup...
Checking if we need to fetch /opt/homebrew/Library/Taps/sidneys/homebrew-homebrew...
Fetching /opt/homebrew...
Fetching /opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade...
Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-bundle...
Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-autoupdate...
Fetching /opt/homebrew/Library/Taps/dart-lang/homebrew-dart...
Fetching /opt/homebrew/Library/Taps/homebrew/homebrew-services...
Fetching /opt/homebrew/Library/Taps/isen-ng/homebrew-dotnet-sdk-versions...
Fetching /opt/homebrew/Library/Taps/lihaoyun6/homebrew-tap...
Fetching /opt/homebrew/Library/Taps/leoafarias/homebrew-fvm...
Fetching /opt/homebrew/Library/Taps/microsoft/homebrew-git...
Fetching /opt/homebrew/Library/Taps/mongodb/homebrew-brew...
Fetching /opt/homebrew/Library/Taps/rstacruz/homebrew-backup...
Fetching /opt/homebrew/Library/Taps/romkatv/homebrew-powerlevel10k...
Fetching /opt/homebrew/Library/Taps/sidneys/homebrew-homebrew...
Checking if we need to fetch formula.jws.json...
Checking if we need to fetch cask.jws.json...
Checking if we need to fetch formula_tap_migrations.jws.json...
Checking if we need to fetch cask_tap_migrations.jws.json...
Error: 16.89.24091630 1-59-15-667 PM.24091630 contains invalid characters:  !
/opt/homebrew/Library/Homebrew/cask/dsl/version.rb:71:in `initialize'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11602/lib/types/private/methods/call_validation_2_7.rb:1547:in `bind_call'
/opt/homebrew/Library/Homebrew/vendor/bundle/ruby/3.3.0/gems/sorbet-runtime-0.5.11602/lib/types/private/methods/call_validation_2_7.rb:1547:in `block in create_validator_procedure_medium1'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:14:in `new'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:14:in `current_version'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:26:in `block in installed_apps'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:22:in `map'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:22:in `installed_apps'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu/command/upgrade.rb:31:in `run_process'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu/command/upgrade.rb:8:in `process'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:24:in `process'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:75:in `<top (required)>'
<internal:/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:11:in `require?'
/opt/homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

**Comment by Sophoria** [comment]
`brew outdated --cask` gives nothing in return

My verbose output for completeness sake:

==> Options
Include auto-update (-a): false
Include latest (-f): false
==> Updating Homebrew
Checking if we need to fetch /opt/homebrew...
==> Updating Homebrew...
Checking if we need to fetch /opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade...
Checking if we need to fetch /opt/homebrew/Library/Taps/homebrew/homebrew-services...
Fetching /opt/homebrew...
Updating /opt/homebrew...
branch 'master' set up to track 'origin/master'.
Reset branch 'stable'
Current branch stable is up to date.
Checking if we need to fetch formula.jws.json...
Checking if we need to fetch cask.jws.json...
Checking if we need to fetch formula_tap_migrations.jws.json...
Checking if we need to fetch cask_tap_migrations.jws.json...
Already up-to-date.
Checking if we need to fetch /opt/homebrew...
Checking if we need to fetch /opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade...
Checking if we need to fetch /opt/homebrew/Library/Taps/homebrew/homebrew-services...
Fetching /opt/homebrew...
Updating /opt/homebrew...
branch 'master' set up to track 'origin/master'.
Current branch stable is up to date.
Checking if we need to fetch formula.jws.json...
Checking if we need to fetch cask.jws.json...
Checking if we need to fetch formula_tap_migrations.jws.json...
Checking if we need to fetch cask_tap_migrations.jws.json...
Already up-to-date.
!contains invalid characters:
/opt/homebrew/Library/Homebrew/cask/dsl/version.rb:71:in `initialize'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:14:in `new'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:14:in `current_version'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:26:in `block in installed_apps'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:22:in `map'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:22:in `installed_apps'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu/command/upgrade.rb:31:in `run_process'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu/command/upgrade.rb:8:in `process'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:24:in `process'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:75:in `<top (required)>'
<internal:/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.3.5/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:11:in `require?'
/opt/homebrew/Library/Homebrew/brew.rb:100:in `<main>'

**Comment by Sophoria** [comment]
Thanks for trying, but I still get the error:


`!contains invalid characters:
/opt/homebrew/Library/Homebrew/cask/dsl/version.rb:71:in 'Cask::DSL::Version#initialize'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:14:in 'String.new'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:14:in 'Cask.current_version'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:26:in 'block in Cask.installed_apps'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:22:in 'Array#map'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/cask.rb:22:in 'Cask.installed_apps'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu/command/upgrade.rb:33:in 'Bcu::Upgrade#run_process'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu/command/upgrade.rb:10:in 'Bcu::Upgrade#process'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:24:in 'Bcu.process'
/opt/homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:75:in '<main>'
<internal:/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.5/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:37:in 'Kernel#require'
<internal:/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.5/lib/ruby/3.4.0/rubygems/core_ext/kernel_require.rb>:37:in 'Kernel#require'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/3.4.5/lib/ruby/gems/3.4.0/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in 'Kernel#require'
/opt/homebrew/Library/Homebrew/utils.rb:17:in 'block in Homebrew.require?'
/opt/homebrew/Library/Homebrew/warnings.rb:29:in 'Warnings.ignore'
/opt/homebrew/Library/Homebrew/utils.rb:16:in 'Homebrew.require?'
/opt/homebrew/Library/Homebrew/brew.rb:116:in '<main>'`

**Comment by Sophoria** [comment]
I got it working after looking at the debug output.  Here's a snippet:

`Checking installed versions for "keka"
Versions: ["1.6.0"]
Checking installed versions for "linphone"
Versions: ["Icon\r"]
!contains invalid characters:
/opt/homebrew/Library/Homebrew/cask/dsl/version.rb:71:in 'Cask::DSL::Version#initialize'`

So it choked up on linphone. I removed linphone a while ago, but I must have done it manually. So, I ran

`brew uninstall --cask linphone --force`

I ran the debug again and it choked up on another app I removed, so I repeated the command for that app and now everything is working again~
