### ISSUE TITLE
Error msg during cleanup

### ISSUE THREAD

**Issue by jrking123** [buo/homebrew-cask-upgrade#61]
Hi, during the sequence:
```
brew cu --all --yes --cleanup
brew cask cleanup
```
The following error is returned. I've seen it on apps other than flux. 
```
==> Found outdated apps
=================================================================
No.  Name   Cask  Current  Latest  Auto-Update  State
=================================================================
1/1  f.lux  flux  39.98    39.981  Y            forced to upgrade
=================================================================
==> Upgrading flux to 39.981
==> Downloading https://justgetflux.com/mac/Flux39.981.zip
######################################################################## 100.0%
==> Verifying checksum for Cask flux
==> Installing Cask flux
Warning: It seems there is already an App at '/Applications/Flux.app'; overwriting.
==> Removing App '/Applications/Flux.app'.
==> Moving App 'Flux.app' to '/Applications/Flux.app'.
🍺  flux was successfully installed!
Error: undefined method `default' for Hbc::CLI::Cleanup:Class
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:47:in `process'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:29:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/brew.rb:25:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:106:in `<main>'
==> Removing cached downloads
/Users/jking/Library/Caches/Homebrew/Cask/flux--39.981.zip
==> This operation has freed approximately 1.7MB of disk space.
```
```
Homebrew-Cask 1.2.2-2-gb9cfd2cb5
caskroom/homebrew-cask (git revision a2b37; last commit 2017-06-05)
```

**Comment by daylightbrightledlight** [comment]
This bug still isn't fixed.
