### ISSUE TITLE
undefined method "default" for Cleanup Class during upgrade

### ISSUE THREAD

**Issue by phdoerfler** [buo/homebrew-cask-upgrade#63]
```
==> Upgrading sonic-visualiser to 3.0.3,2249
==> Satisfying dependencies
==> Downloading https://code.soundsoftware.ac.uk/attachments/download/2249/Sonic%20Visualiser-3.0.3.dmg
######################################################################## 100,0%
==> Verifying checksum for Cask sonic-visualiser
==> Installing Cask sonic-visualiser
Warning: It seems there is already an App at '/Applications/Sonic Visualiser.app'; overwriting.
==> Removing App '/Applications/Sonic Visualiser.app'.
==> Moving App 'Sonic Visualiser.app' to '/Applications/Sonic Visualiser.app'.
🍺  sonic-visualiser was successfully installed!
Error: undefined method `default' for Hbc::CLI::Cleanup:Class
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:47:in `process'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:29:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:20:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
```

**Comment by buo** [comment]
This issue was fixed by PR #64.
