### ISSUE TITLE
Fatal cask token and license deprecation errors

### ISSUE THREAD

**Issue by filler** [buo/homebrew-cask-upgrade#76]
Hello! 👋 

First off, thanks for making `cask-upgrade`!  This is great!  🎉 

I seem to be unable to leverage `brew cu`.

```
 ~/code/work/hyp/hypervisors   master ●  brew cu
==> Options
Include auto-update (-a): false
Include latest (-f): false
==> Updating Homebrew
Already up-to-date.
==> Finding outdated apps
Warning: Calling "cask :v1 => 'token'" is deprecated!
Use "cask 'token'" instead.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:39:in `load_cask'
Please report this to the buo/cask-upgrade tap!

Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:39:in `load_cask'
Please report this to the buo/cask-upgrade tap!

Error: Cask 'dockertoolbox' definition is invalid: Token '{:v1_1=>"dockertoolbox"}' in header line does not match the file name.
 ✘  ~/code/work/hyp/hypervisors   master ●  brew cu -fa
==> Options
Include auto-update (-a): true
Include latest (-f): true
==> Updating Homebrew
Already up-to-date.
==> Finding outdated apps
Warning: Calling "cask :v1 => 'token'" is deprecated!
Use "cask 'token'" instead.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:39:in `load_cask'
Please report this to the buo/cask-upgrade tap!

Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:39:in `load_cask'
Please report this to the buo/cask-upgrade tap!

Error: Cask 'dockertoolbox' definition is invalid: Token '{:v1_1=>"dockertoolbox"}' in header line does not match the file name.
 ✘  ~/code/work/hyp/hypervisors   master ●  brew -v
Homebrew 1.3.1-138-g156bca7
Homebrew/homebrew-core (git revision 5be8e; last commit 2017-08-30)
 ✘  ~/code/work/hyp/hypervisors   master ●  brew cask --version
Homebrew-Cask 1.3.1-138-g156bca7
caskroom/homebrew-cask (git revision b0894; last commit 2017-08-31)
 ✘  ~/code/work/hyp/hypervisors   master ●  brew update
Already up-to-date.
 ~/code/work/hyp/hypervisors   master ●  brew update
Already up-to-date.
 ~/code/work/hyp/hypervisors   master ●  brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/python2.7/greenlet/greenlet.h
 ✘  ~/code/work/hyp/hypervisors   master ●  brew cu
==> Options
Include auto-update (-a): false
Include latest (-f): false
==> Updating Homebrew
Already up-to-date.
==> Finding outdated apps
Warning: Calling "cask :v1 => 'token'" is deprecated!
Use "cask 'token'" instead.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:39:in `load_cask'
Please report this to the buo/cask-upgrade tap!

Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:39:in `load_cask'
Please report this to the buo/cask-upgrade tap!

Error: Cask 'dockertoolbox' definition is invalid: Token '{:v1_1=>"dockertoolbox"}' in header line does not match the file name.
 ✘  ~/code/work/hyp/hypervisors   master ●  brew cu -fa
==> Options
Include auto-update (-a): true
Include latest (-f): true
==> Updating Homebrew
Already up-to-date.
==> Finding outdated apps
Warning: Calling "cask :v1 => 'token'" is deprecated!
Use "cask 'token'" instead.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:39:in `load_cask'
Please report this to the buo/cask-upgrade tap!

Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:39:in `load_cask'
Please report this to the buo/cask-upgrade tap!

Error: Cask 'dockertoolbox' definition is invalid: Token '{:v1_1=>"dockertoolbox"}' in header line does not match the file name.
 ✘  ~/code/work/hyp/hypervisors   master ● 
```

I understand the greenlet header file squawking to be benign based on some quick Googling about.

Thanks so much for taking a look and what you do for open-source! 🙇

**Comment by filler** [comment]
A-ha.  This seems to be related to a cask rename!  Following https://apple.stackexchange.com/a/283404, progress can be made

```
 ✘  /usr/local/Caskroom/dockertoolbox  cd /usr/local/Caskroom

 /usr/local/Caskroom  mv dockertoolbox docker-toolbox
 /usr/local/Caskroom  brew cu
==> Options
Include auto-update (-a): false
Include latest (-f): false
==> Updating Homebrew
Already up-to-date.
==> Finding outdated apps
Warning: Calling "cask :v1 => 'token'" is deprecated!
Use "cask 'token'" instead.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:39:in `load_cask'
Please report this to the buo/cask-upgrade tap!

Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:39:in `load_cask'
Please report this to the buo/cask-upgrade tap!

Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:39:in `load_cask'
Please report this to the buo/cask-upgrade tap!

Warning: Calling "cask :v1 => 'token'" is deprecated!
Use "cask 'token'" instead.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:39:in `load_cask'
Please report this to the buo/cask-upgrade tap!

Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:39:in `load_cask'
Please report this to the buo/cask-upgrade tap!

Warning: Unexpected method 'tags' called on Cask flash.
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
Warning: Calling "cask :v1 => 'token'" is deprecated!
Use "cask 'token'" instead.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:39:in `load_cask'
Please report this to the buo/cask-upgrade tap!

Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:39:in `load_cask'
Please report this to the buo/cask-upgrade tap!

Warning: Unexpected method 'tags' called on Cask google-earth.
Follow the instructions here:
  https://github.com/caskroom/homebrew-cask#reporting-bugs
Error: Cask 'microsoft-lync-plugin' definition is invalid: Token '{:v1_1=>"microsoft-lync-plugin"}' in header line does not match the file name.
```

So it looks like the issue is unrelated to `cask-upgrade` entirely!  Doh!

Thanks!  🌟
