### ISSUE TITLE
Error: cannot load such file -- vendor/homebrew-fork/global

### ISSUE THREAD

**Issue by lamemate** [buo/homebrew-cask-upgrade#8]
After the latest Homebrew update there is an error:

```
brew cu
Error: cannot load such file -- vendor/homebrew-fork/global
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:3:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:1:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:8:in `<top (required)>'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/Homebrew/brew.rb:22:in `require?'
/usr/local/Library/Homebrew/brew.rb:93:in `<main>'
```

The versions I use after the update:
```
brew --version
Homebrew 0.9.9 (git revision b77a6; last commit 2016-08-02)
Homebrew/homebrew-core (git revision c91f; last commit 2016-08-03)

brew cask --version
0.60.0 (git revision 991cb; last commit 2 hours ago)
```

**Comment by adidalal** [comment]
Might be due to  https://github.com/caskroom/homebrew-cask/pull/23359

**Comment by samm-git** [comment]
after commenting out global.rb in the /usr/local/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb it seems to work fine

**Comment by lamemate** [comment]
Thanks @samm-git, that did the trick. I created a pull request with the fix.
