### ISSUE TITLE
Calling MacOS.release is disabled!

### ISSUE THREAD

**Issue by asins** [buo/homebrew-cask-upgrade#89]
```sh
brew cu -facy
==> Options
Include auto-update (-a): true
Include latest (-f): true
==> Updating Homebrew
==> fatal: unable to access 'https://github.com/caskroom/homebrew-cask/': transfer closed with outstanding
==> fatal: unable to access 'https://github.com/Homebrew/homebrew-core/': transfer closed with outstanding
==> Error:
==> Fetching /usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask failed!
==> Fetching /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core failed!

==> Finding outdated apps
Warning: Calling Hbc::DSL#license is deprecated!
There is no replacement.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:41:in `load_cask'
Please report this to the buo/cask-upgrade tap!

Error: Calling MacOS.release is disabled!
Use MacOS.version instead.
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:41:in `load_cask'
Please report this to the buo/cask-upgrade tap!
Or, even better, submit a PR to fix it!
```

**Comment by asins** [comment]
`rm -rf /usr/local/Caskroom/java7/` and `brew cu -facy`  is Ok,
