### ISSUE TITLE
unexpected <<

### ISSUE THREAD

**Issue by Kamik423** [buo/homebrew-cask-upgrade#99]
I had Issue #97 and used the fix there. It worked fine for a few days, now I get

```error
$ brew cu -acy
Error: /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:1: syntax error, unexpected <<
<<<<<<< Updated upstream
  ^
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/extend/hbc.rb:5: syntax error, unexpected ===, expecting end-of-input
=======
   ^
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/lib/bcu.rb:6:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade/cmd/brew-cu.rb:32:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:18:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:105:in `<main>'
```

**Comment by ondrejfuhrer** [comment]
Hey @Kamik423 , this should help:
```
cd /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade && git fetch && git reset --hard origin/master && git pull
```

After that you should be able to run `brew cu -acy` without any issue.

**Comment by Kamik423** [comment]
fixed it, thanks!
